config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :jobs
  resources :freelancers, only: [:index, :show]
  resources :freelancer_profiles, only: [:show, :edit, :update, :new, :create]
  resources :employers, only: [:index, :show]
  resources :conversations, only: [:index, :show, :destroy]
  resources :messages, only: [:new, :create]

  resources :users do
    post 'follow',   to: 'socializations#follow'
    post 'unfollow', to: 'socializations#unfollow'
  end

  resources :jobs do
    post 'like',   to: 'socializations#like'
    post 'unlike', to: 'socializations#unlike'
  end

  resources :conversations, only: [:index, :show, :destroy] do
    member do
      post :reply
      post :restore
      post :mark_as_read
    end
    collection do
      delete :empty_trash
    end
  end

  get 'contact' => 'pages#contact', as: 'contact'
  get 'about' => 'pages#about', as: 'about'
  get 'blogs' => 'pages#blogs', as: 'blogs'
  get 'landing' => 'pages#landing', as: 'landing'
  get 'guide' => 'pages#guide', as: 'guide'
  get 'terms_and_conditions' => 'pages#terms_and_conditions', as: 'terms_and_conditions'
  get 'faq' => 'pages#faq', as: 'faq'
  get 'job_openings' => 'pages#job_openings', as: 'job_openings'

  root 'pages#landing'

end

app/models/job.rb
class Job < ApplicationRecord
  belongs_to :user

  acts_as_likeable

  def self.job_search(query)
     where("title ILIKE ?", "%#{query}%")
  end

  def self.owner(user)
    where(id: user)
  end

end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController

  before_action :authenticate_user!
  load_and_authorize_resource

  def index

    if current_user.freelancer?
      @jobs = @jobs.paginate(page: params[:page], per_page: 25)
      @favorite_jobs = @jobs.where(id: current_user.likees(Job).map(&:id));
      if params[:job_search]
        @jobs = Job.job_search(params[:job_search]).paginate(page: params[:page], per_page: 25)
      else
        @jobs = Job.paginate(page: params[:page], per_page: 20)
      end
    end

    if current_user.employer?
      @jobs = current_user.jobs
      @favorite_jobs = current_user.jobs
    end
  end

  def show
  end

  def new
  end

  def create
    if current_user.employer?
      if current_user.employer_profile?
        @job = Job.new(create_params)
        @job.user_id = current_user.id
        if @job.save
          flash[:success] = "The job was created."
          redirect_to jobs_path
        else
          flash[:error] = "Something went wrong. Please try again."
          render 'new'
        end
      else
        flash[:error] = "Please make a profile first."
        redirect_to root_path
      end
    else
      flash[:error] = "You are not an employer, so you cannot create a job."
    end
  end

  def edit
    @job = Job.find(params[:id])
  end

  def update
    @job = Job.find(params[:id])
    if @job.update_attributes(update_params)
      flash[:success] = "The job has been updated."
      redirect_to jobs_path
    else
      flash[:error] = "Something went wrong. Please try again."
      render 'edit'
    end
  end

  def destroy
    @job = Job.find(params[:id])
    @job.destroy
    flash[:success] = "The job has been deleted."
    redirect_to jobs_path
  end

  private

  def create_params
    params.require( :job ).permit(:title, :business, :description, :city, :country, :fte, :responsibilities, :user_id )
  end

  def update_params
    params.require( :job ).permit(:title, :business, :description, :city, :country, :fte, :responsibilities, :user_id)
  end

end

app/views/jobs/_detail_header.html.erb
<header class="page-header">
  <div class="container">
    <div class="header-detail">
      <div class="hgroup">
        <h1><%= @job.title %></h1>
        <h3><a href="#"><%= @job.user.employer_profile %></a></h3>
      </div>
      <time datetime="2016-03-03 20:00">CREATED_AT</time>
      <hr>
      <p class="lead">SOME DSCRIPTION</p>

      <ul class="details cols-3">
        <li>
          <i class="fa fa-map-marker"></i>
          <span>SOME LOCATION</span>
        </li>

        <li>
          <i class="fa fa-briefcase"></i>
          <span>SOME FTE</span>
        </li>

        <li>
          <i class="fa fa-money"></i>
          <span>SOME FEE</span>
        </li>

        <li>
          <i class="fa fa-clock-o"></i>
          <span>SOME FTE</span>
        </li>

        <li>
          <i class="fa fa-flask"></i>
          <span>SOME EXPERIENCE DMEAND</span>
        </li>

        <li>
          <i class="fa fa-certificate"></i>
          <a href="#">SOME EDUCATION</a>
        </li>
      </ul>

      <div class="button-group">
        <ul class="social-icons">
          <li class="title">Share on</li>
          <li><a class="facebook" href="#"><i class="fa fa-facebook"></i></a></li>
          <li><a class="google-plus" href="#"><i class="fa fa-google-plus"></i></a></li>
          <li><a class="twitter" href="#"><i class="fa fa-twitter"></i></a></li>
          <li><a class="linkedin" href="#"><i class="fa fa-linkedin"></i></a></li>
        </ul>

        <div class="action-buttons">
          <% if can? :update, @job %>
            <%= link_to "Edit job", edit_job_path( @job.id ), class: "btn btn-primary" %>
          <% end %>

          <% if can? :destroy, @job %>
            <%= link_to "Delete job", @job, method: :delete, data: {confirm: "Do you wish to delete #{@job.title}?"}, class: "btn btn-primary" %>
          <% end %>

          <% if current_user.freelancer? %>
            <% if !current_user.likes?(@job) %>
              <%= link_to('Like', job_like_path(@job), method: :post, class: "btn btn-primary") %>
            <% else %>
              <%= link_to('Unlike', job_unlike_path(@job), method: :post, class: "btn btn-primary") %>
            <% end %>
          <% end %>
        </div>
      </div>

    </div>
  </div>
</header>

app/views/jobs/_form.html.erb
<%= form_for @job do |f| %>
<header class="page-header">
  <div class="container page-name">
    <h1 class="text-center">Add a new job</h1>
    <p class="lead text-center">Create a new vacancy for your company and put it online.</p>
  </div>

  <div class="container">

    <div class="row">
      <div class="form-group col-xs-12 col-sm-6">
        <%= f.label :title, class: "sr-only" %>
        <%= f.text_field :title, class: "form-control input-lg", placeholder: "Job title..." %>
      </div>

      <div class="form-group col-xs-12">
        <%= f.label :description, class: "sr-only" %>
        <%= f.text_area :description, placeholder: "Short description", rows: "3", class: "form-control" %>
      </div>

      <div class="form-group col-xs-12">
        <input type="text" class="form-control" placeholder="Application URL">
      </div>

      <div class="form-group col-xs-12 col-sm-6 col-md-4">
        <div class="input-group input-group-sm">
          <span class="input-group-addon"><i class="fa fa-map-marker"></i></span>
          <%= f.label :city, class: "sr-only" %>
          <%= f.text_field :city, class: "form-control", placeholder: "The city" %>
        </div>
      </div>

      <div class="form-group col-xs-12 col-sm-6 col-md-4">
        <div class="input-group input-group-sm">
          <span class="input-group-addon"><i class="fa fa-briefcase"></i></span>
          <select class="form-control selectpicker">
            <option>Full time</option>
            <option>Part time</option>
            <option>Internship</option>
            <option>Freelance</option>
            <option>Remote</option>
          </select>
        </div>
      </div>

      <div class="form-group col-xs-12 col-sm-6 col-md-4">
        <div class="input-group input-group-sm">
          <span class="input-group-addon"><i class="fa fa-money"></i></span>
          <input type="text" class="form-control" placeholder="Salary">
        </div>
      </div>

      <div class="form-group col-xs-12 col-sm-6 col-md-4">
        <div class="input-group input-group-sm">
          <span class="input-group-addon"><i class="fa fa-clock-o"></i></span>
          <%= f.label :fte, class: "sr-only" %>
          <%= f.text_field :fte, class: "form-control", placeholder: "amount of hours per week" %>
          <span class="input-group-addon">hours / week</span>
        </div>
      </div>

      <div class="form-group col-xs-12 col-sm-6 col-md-4">
        <div class="input-group input-group-sm">
          <span class="input-group-addon"><i class="fa fa-flask"></i></span>
          <input type="text" class="form-control" placeholder="Experience, e.g. 5">
          <span class="input-group-addon">Years</span>
        </div>
      </div>

      <div class="form-group col-xs-12 col-sm-6 col-md-4">
        <div class="input-group input-group-sm">
          <span class="input-group-addon"><i class="fa fa-certificate"></i></span>
          <select class="form-control selectpicker" multiple>
            <option>Postdoc</option>
            <option>Ph.D.</option>
            <option>Master</option>
            <option selected>Bachelor</option>
          </select>
        </div>
      </div>


    </div>
  </div>
</header>
<!-- END Page header -->


<!-- Main container -->
<main>

    <!-- Submit -->
    <section class="bg-alt">
      <div class="container">
        <header class="section-header">
          <span>Are you done?</span>
          <h2>Submit Job</h2>
          <p>Please review your information once more and press the below button to put your job online.</p>
        </header>

        <p class="text-center"><%= f.submit (@job.new_record? ? "Create" : "Update"), class: "btn btn-success btn-xl btn-round" %></p>

      </div>
    </section>
    <!-- END Submit -->


</main>
<% end %>

app/views/jobs/_header.html.erb
<header class="page-header header-job-search">
  <div class="container page-name">
    <h1 class="text-center">Browse jobs</h1>
    <p class="lead text-center">Find your challenge!</p>
  </div>
  <div class="container">
    <%= form_tag '/employers', :method => "get", id: "search-form", class: "header-job-search" do %>
      <div class="row">
        <div class="form-group col-xs-12">
           <%= search_field_tag :job_search, params[:job_search], placeholder: "insert a search query here", autofocus: true, class: "form-control" %>
        </div>
      </div>
      <div class="button-group">
        <div class="action-buttons">
          <%= submit_tag "Search", :name => nil, id: "search-form", class: "btn btn-primary" %>
        </div>
        <div class="action-buttons">
          <% if can? :create, Job %>
            <%= link_to "New job", new_job_path, class: "btn btn-primary" %>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</header>

app/views/jobs/index.html.erb
<!-- FAVORITE JOBS  -->
<!-- <% @favorite_jobs.each do |favorite| %>
  <%= favorite.title %>
<% end %> -->
<!-- END FAVORITE JOBS -->

<%= render "header" %>

<main>
  <section class="no-padding-top bg-alt">
    <div class="container">
      <div class="row">

        <% @jobs.each do |job| %>

          <div class="col-xs-12">
            <%= link_to job_path(job.id), class: "item-block" do %>
              <header>
                <div class="hgroup">
                  <h4><%= job.title %></h4>
                  <h5><%= job.business %><span class="label label-success"><%= job.fte %></span></h5>
                </div>
                <time datetime="2016-03-10 20:00"><%= job.created_at %></time>
              </header>

              <div class="item-body">
                <p><%= job.description %></p>
              </div>

              <footer>
                <ul class="details cols-3">
                  <li>
                    <i class="fa fa-map-marker"></i>
                    <span><%= job.city %>, <%= job.country %></span>
                  </li>

                  <li>
                    <i class="fa fa-money"></i>
                    <span><%= job.pay_rate_minimum %> - <%= job.pay_rate_maximum %></span>
                  </li>

                  <li>
                    <i class="fa fa-certificate"></i>
                    <span><%= job.education_requirement %></span>
                  </li>
                </ul>
              </footer>
              <hr>

              <% end %>

          </div>
        <% end %>
      </div>
    </div>
  </section>
</main>

app/views/jobs/show.html.erb
<%= render 'detail_header' %>