config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :jobs
  resources :freelancers, only: [:index, :show]
  resources :freelancer_profiles, only: [:show, :edit, :update, :new, :create]
  resources :employers, only: [:index, :show]
  resources :conversations, only: [:index, :show, :destroy]
  resources :messages, only: [:new, :create]

  resources :users do
    post 'follow',   to: 'socializations#follow'
    post 'unfollow', to: 'socializations#unfollow'
  end

  resources :jobs do
    post 'like',   to: 'socializations#like'
    post 'unlike', to: 'socializations#unlike'
  end

  resources :conversations, only: [:index, :show, :destroy] do
    member do
      post :reply
      post :restore
      post :mark_as_read
    end
    collection do
      delete :empty_trash
    end
  end

  get 'contact' => 'pages#contact', as: 'contact'
  get 'about' => 'pages#about', as: 'about'
  get 'blogs' => 'pages#blogs', as: 'blogs'
  get 'landing' => 'pages#landing', as: 'landing'
  get 'guide' => 'pages#guide', as: 'guide'
  get 'terms_and_conditions' => 'pages#terms_and_conditions', as: 'terms_and_conditions'
  get 'faq' => 'pages#faq', as: 'faq'
  get 'job_openings' => 'pages#job_openings', as: 'job_openings'

  root 'pages#landing'

end

app/controllers/employers_controller.rb
class EmployersController < ApplicationController

  before_action :authenticate_user!

  # Employer is role_id 2 (1 is for freelancers)

  def index
    if current_user.freelancer?
      if params[:employer_search]
        @employers = User.where(role_id: 2).employer_search(params[:employer_search]).order("created_at DESC").paginate(page: params[:page], per_page: 25)
      else
        @employers = User.where(role_id: 2).paginate(page: params[:page], per_page: 20)
      end
    else
      flash[:error] = "I'm sorry, this page is restricted."
      redirect_to root_path
    end
  end

  def show
    if current_user.freelancer?
      employer = User.where(role_id: 2)
      @employer = employer.find(params[:id])
    else
      flash[:error] = "I'm sorry, this page is restricted."
      redirect_to root_path
    end
  end

end

app/views/employers/_detail_header.html.erb
<header class="page-header">
  <div class="container">
    <div class="header-detail">
      <div class="hgroup">
        <h1>SOME_NAME | <%= @employer.first_name %> <%= @employer.last_name %></h1>
        <h3>SOME_BUSINESS</h3>
      </div>
      <hr>
      <p class="lead">SOME_DESCRIPTION</p>

      <ul class="details cols-3">
        <li>
          <i class="fa fa-map-marker"></i>
          <span>SOME_LOCATION</span>
        </li>

        <li>
          <i class="fa fa-globe"></i>
          <a href="#">SOME_WEBSITE</a>
        </li>

        <li>
          <i class="fa fa-envelope"></i>
          <a href="#">SOME_EMAIL</a>
        </li>
      </ul>

      <div class="button-group">
        <ul class="social-icons">
          <li><a class="facebook" href="#"><i class="fa fa-facebook"></i></a></li>
          <li><a class="twitter" href="#"><i class="fa fa-twitter"></i></a></li>
          <li><a class="dribbble" href="#"><i class="fa fa-dribbble"></i></a></li>
          <li><a class="linkedin" href="#"><i class="fa fa-linkedin"></i></a></li>
          <li><a class="instagram" href="#"><i class="fa fa-instagram"></i></a></li>
        </ul>

        <div class="action-buttons">
          <% if !current_user.follows?(@employer) %>
            <%= link_to user_follow_path(@employer), method: :post, class: "btn btn-success" do %>
              follow
              <i class="fa fa-star" aria-hidden="true"></i>
            <% end %>
          <% else %>
            <%= link_to user_unfollow_path(@employer), method: :post, class: "btn btn-gray" do %>
              unfollow
              <i class="fa fa-star-o" aria-hidden="true"></i>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</header>

app/views/employers/_header.html.erb
<header class="page-header">
  <div class="container page-name">
    <h1 class="text-center">Browse employer representatives</h1>
    <p class="lead text-center">Find representatives that are looking for people like you!</p>
  </div>
  <div class="container">
    <%= form_tag '/employers', :method => "get", id: "search-form", class: "header-job-search" do %>
      <div class="row">
        <div class="form-group col-xs-12">
           <%= search_field_tag :employer_search, params[:employer_search], placeholder: "insert a search query here", autofocus: true, class: "form-control" %>
        </div>
      </div>
      <div class="button-group">
        <div class="action-buttons">
          <%= submit_tag "Search", :name => nil, id: "search-form", class: "btn btn-primary" %>
        </div>
      </div>
    <% end %>
  </div>
</header>

app/views/employers/index.html.erb
<%= render 'header' %>

<main>
  <section class="no-padding-top bg-alt">
    <div class="container">
      <div class="row">
        <% @employers.each do |employer| %>
        <div class="col-xs-12">
          <%= link_to employer_path(employer), class: "item-block" do %>
            <header>
              <div class="hgroup">
                <h4>SOME_COMPANY_NAME | <%= employer.first_name %> <%= employer.last_name %></h4>
              </div>
              <time datetime="2016-03-10 20:00">34 min ago</time>
            </header>

            <div class="item-body">
              <p>SOME_DESCRIPTION_HERE</p>
            </div>

            <footer>
              <ul class="details cols-3">


                <li>
                  <i class="fa fa-money"></i>
                  <span>AVERAGE_PAY_HERE</span>
                </li>

                <li>
                  <i class="fa fa-briefcase"></i>
                  <span>SOME_BUSINESS_HERE</span>
                </li>
              </ul>
            </footer>
          <% end %>
        </div>
        <% end %>
      </div>
    </div>
  </section>
</main>