config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :jobs
  resources :freelancers, only: [:index, :show]
  resources :freelancer_profiles, only: [:show, :edit, :update, :new, :create]
  resources :employers, only: [:index, :show]
  resources :conversations, only: [:index, :show, :destroy]
  resources :messages, only: [:new, :create]

  resources :users do
    post 'follow',   to: 'socializations#follow'
    post 'unfollow', to: 'socializations#unfollow'
  end

  resources :jobs do
    post 'like',   to: 'socializations#like'
    post 'unlike', to: 'socializations#unlike'
  end

  resources :conversations, only: [:index, :show, :destroy] do
    member do
      post :reply
      post :restore
      post :mark_as_read
    end
    collection do
      delete :empty_trash
    end
  end

  get 'contact' => 'pages#contact', as: 'contact'
  get 'about' => 'pages#about', as: 'about'
  get 'blogs' => 'pages#blogs', as: 'blogs'
  get 'landing' => 'pages#landing', as: 'landing'
  get 'guide' => 'pages#guide', as: 'guide'
  get 'terms_and_conditions' => 'pages#terms_and_conditions', as: 'terms_and_conditions'
  get 'faq' => 'pages#faq', as: 'faq'
  get 'job_openings' => 'pages#job_openings', as: 'job_openings'

  root 'pages#landing'

end

app/views/layouts/_flashes.html.erb
<% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>">
      <%= value %>
    </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="site-footer">

  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-6">
        <h6>About</h6>
        <p class="text-justify">Earn your worth by taking matters into your own hands. Stop recruiters from treating your resume like a harlot. You can handle your own negotiations with employers. </p>
      </div>

      <div class="col-xs-6 col-md-3">
        <h6>Company</h6>
        <ul class="footer-links">
          <li><%= link_to "Terms and conditions", terms_and_conditions_path %></li>
          <li><%= link_to "Blogs", blogs_path %></li>
          <li><%= link_to "FAQ", faq_path %></li>
          <li><%= link_to "About", about_path %></li>
          <li><%= link_to "Contact", contact_path %></li>
        </ul>
      </div>

    </div>

    <hr>
  </div>

  <div class="container">
    <div class="row">
      <div class="col-md-8 col-sm-6 col-xs-12">
        <p class="copyright-text">Copyrights &copy; 2016 All Rights Reserved by NAME_HERE.</p>
      </div>

      <div class="col-md-4 col-sm-6 col-xs-12">
        <ul class="social-icons">
          <li><a class="facebook" href="#"><i class="fa fa-facebook"></i></a></li>
          <li><a class="twitter" href="#"><i class="fa fa-twitter"></i></a></li>
          <li><a class="dribbble" href="#"><i class="fa fa-dribbble"></i></a></li>
          <li><a class="linkedin" href="#"><i class="fa fa-linkedin"></i></a></li>
          <li><a class="instagram" href="#"><i class="fa fa-instagram"></i></a></li>
        </ul>
      </div>
    </div>
  </div>

</footer>

app/views/layouts/_navigation.html.erb
<nav class="navbar">
  <div class="container">

    <!-- Logo -->
    <div class="pull-left">
      <a class="navbar-toggle" href="#" data-toggle="offcanvas"><i class="ti-menu"></i></a>

      <div class="logo-wrapper">
        <a class="logo" href="index.html"><img src="assets/img/logo.png" alt="logo"></a>
        <a class="logo-alt" href="index.html"><img src="assets/img/logo-alt.png" alt="logo-alt"></a>
      </div>

    </div>
    <!-- END Logo -->

    <!-- User account -->
    <div class="pull-right user-login">
      <% if !user_signed_in? %>
        <%= link_to 'Log In', new_user_session_path, class: "btn btn-sm btn-primary" %>
        or
        <%= link_to 'Register', new_user_registration_path, class: "btn btn-sm btn-primary" %>
      <% else %>
        <%= link_to 'Log Out', destroy_user_session_path, method: :delete, class: "btn btn-sm btn-primary" %>
      <% end %>
    </div>
    <!-- END User account -->

    <!-- Navigation menu -->

    <ul class="nav-menu">

      <% if user_signed_in? %>
        <li>
          <%= link_to "Jobs", jobs_path %>
        </li>
      <% end %>

      <% if user_signed_in? && current_user.freelancer?%>
        <li>
          <%= link_to "Employers", employers_path %>
        </li>
      <% end %>

      <% if user_signed_in? && current_user.employer?%>
        <li>
          <%= link_to "Freelancers", freelancers_path %>
        </li>
      <% end %>

      <% if user_signed_in? %>

      <li><%= link_to 'Messages', conversations_path %></li>
      <li>
        <%= link_to "Account & Profile", edit_user_registration_path %>
        <ul>
          <% if current_user.freelancer? %>
            <% if current_user.freelancer_profile %>
            <li><%= link_to 'Edit profile', edit_freelancer_profile_path(current_user.freelancer_profile.id) %></li>
            <% else %>
            <li><%= link_to 'New profile', new_freelancer_profile_path %></li>
            <% end %>
          <% end %>
          <li><%= link_to 'Edit account', edit_user_registration_path %></li>
        </ul>
      </li>
      <% end %>

      <li>
        <%= link_to "NAME HERE", about_path %>
        <ul>
          <li><%= link_to "Terms and conditions", terms_and_conditions_path %></li>
          <li><%= link_to "Blogs", blogs_path %></li>
          <li><%= link_to "FAQ", faq_path %></li>
          <li><%= link_to "About", about_path %></li>
          <li><%= link_to "Contact", contact_path %></li>
        </ul>
      </li>
    </ul>
    <!-- END Navigation menu -->

  </div>
</nav>
<!-- END Navigation bar -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IA</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>

    <% if
      current_page?(new_user_registration_path) ||
      current_page?(edit_user_registration_path)||
      current_page?(new_user_session_path) ||
      current_page?(new_user_password_path) ||
      current_page?(edit_user_password_path)
    %>

      <body class="login-page">

    <% else %>

      <body>

    <% end %>

    <%= render "layouts/navigation" %>

    <%= render "layouts/flashes" %>

    <%= yield %>

    <%= render "layouts/footer" %>

  </body>
</html>